---

kind: pipeline
name: deployment

steps:
- name: build
  image: node
  commands:
  - npm ci
  - npm run build
- name: test
  image: node
  commands:
  - npm test
- name: deploy to prod
  image: alpine
  secrets: [ ssh_key ]
  commands:
    - apk add rsync openssh-client
    - eval `ssh-agent -s`
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - rsync -e "ssh -o StrictHostKeyChecking=no" -r ./* vylpes@192.168.68.120:/home/vylpes/apps/card-drop/card-drop_prod
    - ssh vylpes@192.168.68.120 cd ~/apps/card-drop/card-drop_prod && docker compose --file docker-compose.prod.yml up -d && sleep 10 && pm2 start --name card-drop_prod dist/bot.js

trigger:
  event:
  - tag

---

kind: pipeline
name: staging

steps:
- name: build
  image: node
  commands:
  - npm ci
  - npm run build
- name: test
  image: node
  commands:
  - npm test
- name: deploy to stage
  image: alpine
  secrets: [ ssh_key ]
  commands:
    - apk add rsync openssh-client
    - eval `ssh-agent -s`
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - rsync -e "ssh -o StrictHostKeyChecking=no" -r ./* vylpes@192.168.68.120:/home/vylpes/apps/card-drop/card-drop_stage
    - ssh vylpes@192.168.68.120 cd ~/apps/card-drop/card-drop_stage && docker compose --file docker-compose.stage.yml up -d && sleep 10 && pm2 start --name card-drop_stage dist/bot.js

trigger:
  branch:
  - develop
  event:
  - push

---

kind: pipeline
name: integration

steps:
- name: build
  image: node
  commands:
  - npm ci
  - npm run build
- name: test
  image: node
  commands:
  - npm test

trigger:
  branch:
  - hotfix/*
  - feature/*
  - renovate/*
  event:
  - push
