#cloud-config

users:
  - default
  - name: vylpes
    primary-group: vylpes
    shell: /bin/bash
    groups: users, docker, sudo
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExjBL5StgItBG853s9ffDmdLEzssj8l2p1RdfhoT/vU vylpes@Ethans-Mac-mini.lan
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/debian $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    nodejs.list:
    source: deb [signed-by=$KEY_FILE] https://deb.nodesource.com/node_20.x $RELEASE main
    keyid: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280

packages:
  - git
  - rclone
  - rsync
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - nodejs
  - npm
  - python3
  - python3-pip

runcmd:
  - ufw limit ssh
  - ufw enable
  - npm install -g yarn pm2
  - git clone https://github.com/timothymiller/cloudflare-ddns.git /home/vylpes/ddns
  - cp /home/vylpes/ddns/config-example.json /home/vylpes/ddns/config.json
  - chown -R vylpes:vylpes /home/vylpes/ddns
  - chmod +x /home/vylpes/ddns/start-sync.sh
  - echo "*/15 * * * * /home/vylpes/ddns/start-sync.sh" > /home/vylpes/COPY-TO-CRONTAB.txt
  - mkdir /home/vylpes/app && chown -R vylpes:vylpes /home/vylpes/app
  - mkdir /home/vylpes/data && chown -R vylpes:vylpes /home/vylpes/data